### ISSUE TITLE
Failed to determine version of "something" while parsing a yarn.lock - please report this!

### ISSUE THREAD

**Issue by AxetNord** [google/osv-scanner#102]
I don't know, where i may report about this. Report here.
[yarn.lock.txt](https://github.com/google/osv-scanner/files/10306499/yarn.lock.txt)

**Comment by G-Rath** [comment]
Thanks, this is the right place to report this - I'll have a look tomorrow morning, but in the meantime it would be useful to know more about your project to better understand why your `yarn.lock` is structured as it is (assuming it's not just invalid).

Could you also confirm that running `yarn install` doesn't change the lock at all?

**Comment by AxetNord** [comment]
before `yarn install`
[please report this.txt](https://github.com/google/osv-scanner/files/10306644/please.report.this.txt)
After `yarn install` no errors found. Sorry for that

**Comment by G-Rath** [comment]
@AxetNord good to know, though it looks like this happened because your `yarn.lock` has properties quoted e.g.:

```
"word-wrap@^1.2.3":
  "integrity" "sha512-Hz/mrNwitNRh/HUAtM/VT/5VH+ygD6DV7mYKZAtHOrbs8U7lvPS6xf7EJKMF0uW1KJCl0H701g3ZGus+muE5vQ=="
  "resolved" "https://registry.npmjs.org/word-wrap/-/word-wrap-1.2.3.tgz"
  "version" "1.2.3"
```

Instead of:

```
"word-wrap@^1.2.3":
  integrity "sha512-Hz/mrNwitNRh/HUAtM/VT/5VH+ygD6DV7mYKZAtHOrbs8U7lvPS6xf7EJKMF0uW1KJCl0H701g3ZGus+muE5vQ=="
  resolved "https://registry.npmjs.org/word-wrap/-/word-wrap-1.2.3.tgz"
  version "1.2.3"
```

which is something that should be very easy to support but it would be useful to know how your `yarn.lock` got like that first - initially I wondered if it was because of the earlier versions of `yarn` but I've tried all the way back to v0.15.3 with no success.
