### ISSUE TITLE
vulnerability scan of OSS source code

### ISSUE THREAD

**Issue by ahuan2616** [google/osv-scanner#112]
Does osv-scanner support vulnerability scan of OSS source code? 
By reading the documentation and testing, I think it is not supported, but I would like to do a double confirm, thanks !

**Comment by oliverchang** [comment]
Hi, can you clarify what you mean?

This scanner currently focuses on scanning the dependencies in a project, by scanning for e.g. lockfiles and package manifest files rather than scanning source code directly. 

We do have plans to combine this with some source code analysis (#11), with vendored code detection for C/C++ source code.

**Comment by ahuan2616** [comment]
Hi Oliver,
Thank you for your detailed explanation! You have answered my questions. 
My question is whether osv-scanner can support source code analysis，such as C/C++ that using open source files.
