### ISSUE TITLE
Reenable `revive` golangci-lints

### ISSUE THREAD

**Issue by another-rex** [google/osv-scanner#1257]
It looks like by default, golangci has some preset for revive. By disabling a single rule (increment-decrement), this somehow disables all revive rules.

We should re-enable revive, as it is the replacement for golint. This is not trival, as there are quite a few changes we need to make for it to be compliant with revive again.

**Comment by G-Rath** [comment]
fwiw I did realise and look into this a while ago, and found only https://github.com/google/osv-scanner/pull/997 to be worth enabling at the time.

While I didn't write up any detailed notes, I believe my overall findings were:
  - a lot of what's being linted is already been covered by other enabled lints (or in fact clash with them)
  - some would require breaking changes, and didn't seem like something we cared strongly about based on existing code (e.g. stuttering and `unexported-return`)
  - there didn't seem to be any complaints, common mistakes, dislikes, etc slipping through to make it worth chasing these

I'm not against working towards re-enabling `revive`, but I think it would be best to start by capturing a list or table of all the rules that should be (re)enabled so that we can easily work through them and also coordinate with the upcoming v2. 

I also think ideally we should be trying to enable the rules we're addressing for as we go to ensure we don't regress - that could be done either by a file-by-file, package-by-package, or by enabling across the whole codebase and explicitly disabling the rule inline for existing violations (happy to do a PR or two to showcase what I mean if that's not clear).

**Comment by michaelkedar** [comment]
> some would require breaking changes, and didn't seem like something we cared strongly about based on existing code (e.g. stuttering and unexported-return)

fwiw, running `revive` with defaults, the only things I see that are not in `internal`  and would be breaking changes are:
```
pkg/config/config.go:18:6: exported: type name will be used as config.ConfigManager by other packages, and that stutters; consider calling this Manager (revive)
type ConfigManager struct {
     ^
pkg/osvscanner/osvscanner.go:67:5: error-naming: error var NoPackagesFoundErr should have name of the form ErrFoo (revive)
var NoPackagesFoundErr = errors.New("no packages found in scan")
    ^
pkg/osvscanner/osvscanner.go:73:5: error-naming: error var VulnerabilitiesFoundErr should have name of the form ErrFoo (revive)
var VulnerabilitiesFoundErr = errors.New("vulnerabilities found")
    ^
pkg/osvscanner/osvscanner.go:78:5: error-naming: error var OnlyUncalledVulnerabilitiesFoundErr should have name of the form ErrFoo (revive)
var OnlyUncalledVulnerabilitiesFoundErr = errors.New("only uncalled vulnerabilities found")
    ^
```
We already have `//nolint:errname` for the errors, so we can disable one of the rules. So that just leaves the `config.ConfigManager` stuttering, which we can ignore inline.

The majority of our failures seem to be `unused-parameter`, which should be a simple and unintrusive to change.
