### ISSUE TITLE
Version flag returns non-specific information

### ISSUE THREAD

**Issue by hayleycd** [google/osv-scanner#239]
I ran `osv-scanner --version` today and got the following:

```
osv-scanner version: dev
commit: n/a
built at: n/a
```

I expected to see 1.2.

**Comment by another-rex** [comment]
Where was the osv-scanner binary that you ran come from? The version downloaded from github releases show the correct version:

```
$ ./osv-scanner_1.2.0_linux_amd64 --version 
osv-scanner version: 1.2.0
commit: 9647b493034ab334e071921becde06bad8de059e
built at: 2023-02-23T01:27:34Z
```

**Comment by hayleycd** [comment]
I used go install on my work virtual desktop. I also tried homebrew on my personal MacOS and got the same thing.

**Comment by another-rex** [comment]
So currently we inject the version information in the .goreleaser build process, so when you build from source (which homebrew and go install both do), it doesn't have any version info. 

That's not ideal but I'm not 100% sure how to go about fixing this. Maybe https://pkg.go.dev/runtime/debug#ReadBuildInfo could be used by default?

Another option is to update homebrew to use our binary builds rather than building from source, but I'm not familiar enough with how homebrew works to know if this is possible.

**Comment by another-rex** [comment]
Actually looking at this, having homebrew use our binaries is not ideal: https://docs.brew.sh/Acceptable-Formulae#we-dont-like-binary-formulae

**Comment by oliverchang** [comment]
> Maybe https://pkg.go.dev/runtime/debug#ReadBuildInfo could be used by default?

This sounds promising. What does this return exactly? A Go pseudoversion?

**Comment by another-rex** [comment]
It just provides the git tag version (e.g. v1.2.0). So the commit field will still be unpopulated.

Another option is using go generate described here: https://levelup.gitconnected.com/a-better-way-than-ldflags-to-add-a-build-version-to-your-go-binaries-2258ce419d2d

**Comment by another-rex** [comment]
Fixed by including the version in the source code, updating it when doing a release.
