### ISSUE TITLE
go.mod `replace` not being taken into account when reading

### ISSUE THREAD

**Issue by another-rex** [google/osv-scanner#30]
For example, Kubernetes go.mod has these lines:
```
require k8s.io/client-go v0.0.0
...
k8s.io/client-go => ./staging/src/k8s.io/client-go
```

and osv-scanner will incorrectly show all vulnerabilities for client-go that have introduced 0.

**Comment by oliverchang** [comment]
CC @G-Rath

**Comment by G-Rath** [comment]
Ok so there's a bug here that I'm not handling `replace` directives when parsing `go.mod`, which I've got a fix for, but the second part about showing all vulnerabilities is because there isn't a version specified for the replacement so it falls back to assuming it could be impacted by all vulnerabilities since that is the worse case.

In some cases it can be possible to determine a reasonable version to assume (e.g. npm packages require a `package.json` which can have a `version` property, even if they're locally referenced), but that's not the case for Go modules.

This could be improved by doing stuff with git commit shas and/or static code analysis stuff, but I don't think either of them can be considered a guaranteed fixed.
