### ISSUE TITLE
Distinguish between normal and dev dependencies.

### ISSUE THREAD

**Issue by michaelkedar** [google/osv-scanner#332]
There is no current way to identify whether a vulnerable dependency only affects the development environment e.g. whether it comes from `devDependencies` or `dependencies` in `package.json`.

We should add a field to the output to present this information, if we can extract it.

**Comment by aniruth37** [comment]
I tried adding a column called `DevDependency` to the output table. Would the below output resolve this issue?

![image](https://github.com/google/osv-scanner/assets/36035280/7221c0d7-63ee-48ef-b2a2-424f8b3dd733)

**Comment by another-rex** [comment]
We are thinking of placing the devDependencies in a separate table under the normal dependencies. 

So if we identify any dep dependencies, we will print two tables, with the first table containing only main deps, and a second table containing dev deps.

**Comment by G-Rath** [comment]
@another-rex probably better to have support for marking "groups" that packages belong to, to support arbitrary groupings and have the default of no group take priority (since that is typically what are considered production dependencies); then in your output you just print-by-group and naturally sort "no group" to the top

**Comment by oliverchang** [comment]
@cuixq This might be an interesting starter project to tackle.
