### ISSUE TITLE
Regexp compilation taking a long time

### ISSUE THREAD

**Issue by another-rex** [google/osv-scanner#333]
It was noted that in some workloads regexp compliation is taking up to 60% of osv-scanner's runtime.

Especially this line: https://github.com/google/osv-scanner/blob/26c9df8ad0e891dda69f9a620b638710bcd49da2/pkg/lockfile/parse-yarn-lock.go#L114

A solution would be to store the result of the compilation, rather than compiling every time. 

FYI @spencerschrock

**Comment by G-Rath** [comment]
Interesting - do you have any more details you can share? I went back and forward over this for a while, including doing benchmarking especially because of this [this huge regexp](https://github.com/google/osv-scanner/blob/main/internal/semantic/version-pypi.go#L140) because that is large enough that it adds a few seconds to the test suite.

However at runtime I found there wasn't a significant difference which I assumed was due to Go internally caching some things that it didn't do when the tests were being run in parallel, and moving all those regexp compiles out into variables would mean their compilation cost has to be paid regardless of if the related function is actually used.

I had also trailed a JIT-based approach but again found no significant difference in my benchmarks.

**Comment by spencerschrock** [comment]
So this came from profiling Scorecard's cron, which repeatedly calls `osvscanner.DoScan`. Selfishly, a one-time cost is better for my use, which is not a typical use case of osv-scanner.

`lockfile.Parse` 6.54s -> 
(`lockfile.parseYarnPackageGroup` 1.64s +  `lockfile.ParseNpmLock` 4.75s)  ->
 `lockfile.tryExtractCommit` 4.86s -> 
 `regexp.MustCompile` 4.39s


> whereas moving all those regexp compiles out into variables would mean their compilation cost has to be paid regardless of if the related function is actually used

Which is a valid concern for the common case. 
Would a package variable but lazy init be better? Perhaps behind a `sync.Once.Do` ?

**Comment by G-Rath** [comment]
I'm assuming that is the total time across all calls rather than the time of a single call.

> Would a package variable but lazy init be better? Perhaps behind a sync.Once.Do ?

That would be the preferable option - as I said, when I tried this I didn't see any significant difference in my benchmarking to consider it worth the readability cost, but I didn't know `sync.Once.Do` was a thing and that might make it a bit nicer.

(it also is entirely possible I mucked up my benchmarking 🤷)
