### ISSUE TITLE
Better support for transitive deps in Maven/Java (pom.xml) 

### ISSUE THREAD

**Issue by oliverchang** [google/osv-scanner#35]
Currently pom.xml support does not support resolving the full dependency graph.

**Comment by brampat** [comment]
I can't find any documentation on the Maven integration for the scanner. Can anyone point me to it?

**Comment by abhisek** [comment]
@oliverchang Can data from deps.dev be used to resolve transitive dependencies from direct dependencies identified from `pom.xml`? If so, no external tool/plugin will be required to get full list of dependencies.

**Comment by h4sh5** [comment]
Could it have something to with an effective pom? 

https://maven.apache.org/plugins/maven-help-plugin/effective-pom-mojo.html

https://medium.com/@harun_ergul/what-is-effective-pom-5c278fe53031

**Comment by h4sh5** [comment]
`mvn dependency:list` might also help (found in https://github.com/opensbom-generator/spdx-sbom-generator/search?q=mvn)

**Comment by davidrabinowitz** [comment]
Also there's a need to configure maven profiles, as some project build different artifacts based on the profile, see https://github.com/GoogleCloudDataproc/spark-bigquery-connector for example

**Comment by bestbeforetoday** [comment]
Based on the suggestion by @h4sh5 above, my current work-around is to run something like this:

```bash
mvn help:effective-pom -Doutput="${TMPDIR}/pom.xml"
osv-scanner --lockfile="${TMPDIR}/pom.xml"
```

**Comment by oliverchang** [comment]
Thanks for the suggestions all! 

I think it may make sense to support a mode to use ecosystem-specifc tooling (e.g. `mvn`) to achieve this, but we're hoping to avoid adding additional dependnencies, and there are additional complexities around profiles/environments as pointed out in @davidrabinowitz. 

We're also exploring approaches using deps.dev as well to resolve this natively without requiring external tooling. We'll keep this bug updated with any new info!

**Comment by bestbeforetoday** [comment]
I found that, since I really care about the dependencies (including transitive dependencies) that will be on the classpath at runtime, and required by any consuming packages, the approach that actually works for me is to generate a Software Bill of Materials (SBOM) and run OSV-Scanner against that SBOM instead of the POM file.

I currently have the [CycloneDX Maven plugin](https://github.com/CycloneDX/cyclonedx-maven-plugin) configured in a profile within my POM file:
```xml
<profile>
  <id>sbom</id>
  <build>
    <plugins>
      <plugin>
        <groupId>org.cyclonedx</groupId>
        <artifactId>cyclonedx-maven-plugin</artifactId>
        <version>2.7.9</version>
        <configuration>
          <includeCompileScope>true</includeCompileScope>
          <includeProvidedScope>false</includeProvidedScope>
          <includeRuntimeScope>true</includeRuntimeScope>
          <includeSystemScope>false</includeSystemScope>
          <includeTestScope>false</includeTestScope>
        </configuration>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>makeAggregateBom</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</profile>
```

I use this to generate the SBOM, then run OSV-Scanner run against the SBOM:

```bash
mvn --activate-profiles sbom -DskipTests install
osv-scanner --sbom=target/bom.json
```

If anyone has a better solution, I would really like to hear it.

**Comment by LironJit** [comment]
Hi @oliverchang, are there any news re Maven support for transitive dependencies? 
Thanks in advance! :)

**Comment by cuixq** [comment]
Hi @LironJit, we are actively working on this! The changes to resolve Maven projects are on their way. :)

**Comment by oliverchang** [comment]
@cuixq with https://github.com/google/deps.dev/tree/main/util/resolve/maven now being available, do we just need to integrate that into OSV-Scanner?

**Comment by cuixq** [comment]
@oliverchang yes, I think so - I just started working on this!

**Comment by yan-foto** [comment]
Without reopening this issue: relying on `deps.dev` is not going to solve the issue when using the scanner offline (`--offline`). I suppose an easy workaround would be to also parse `<dependencyManagement>` (part of effective POM) and include those dependencies in the scan.

**Comment by cuixq** [comment]
Hi @yan-foto we cannot extract transitive dependency from pom.xml with the offline mode since we need to make network requests for project metadata. 

We now depend on [osv-scalibr](https://github.com/google/osv-scalibr) for dependency extraction and [pomxml extractor](https://github.com/google/osv-scalibr/blob/main/extractor/filesystem/language/java/pomxml/pomxml.go) will be used for pom.xml in offline mode.

Dependencies in [`<dependencyManagement>`](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Management) are not real dependencies so we do not include those in our extracted packages.

**Comment by cuixq** [comment]
@yan-foto no worries! Glad to see that the problem is solved. 

Fully understand that you don't want to send the information to `deps.dev` or other online services. We do have an option to specify native Maven [data source](https://github.com/google/osv-scanner/blob/main/cmd/osv-scanner/scan/source/command.go#L54) which uses Maven Central as the default repository. However requests may still be sent to `osv.dev` for matching vulnerabilities.

**Comment by yan-foto** [comment]
@cuixq, cheers! If I get it right, using `--offline` flag practically avoids sending any requests to `osv.dev`, right? That solves the problem of leaking dependencies and vulns to `osv.dev`.

The second problem, for which I proposed the [workaround](https://github.com/google/osv-scanner/issues/35#issuecomment-2845782655), is a bit more complicated if you use multiple repos (enterprise, private, etc.), so that even the  `--maven-registry` [flags](https://google.github.io/osv-scanner/supported-languages-and-lockfiles/#data-source) does not fully cover the case. 

I suppose the best solution would be to have `osv-scalibr` mimic `mvn`  (read `settings.xml`, resolve dependencies, etc.) but I also understand that it is a rather tedious task with not much added value. So for the time being, I'm going to stick to the workaround 😅 

Thanks for the help and quick response!

**Comment by cuixq** [comment]
Yes you are correct - using `--offline` flag will avoid all network requests so no requests will be sent to `osv.dev` (or any other services).

We do have an issue https://github.com/google/osv-scalibr/issues/409 for reading `settings.xml` for more accurate scanning results, and as I mentioned, to resolve dependencies, we have to make network requests.

**Comment by yan-foto** [comment]
I think `--offline` is not the correct term for what I need here, so my bad for using it!

The resolution on its own is not problematic when requests originate locally and contact some (public/private) repositories. My problem begins when the request is directed at a third party service such as `osv.dev`. So the flag would be something like `--no-thirdparty` to confine the communication with services that the developer already uses. Does that make sense?

**Comment by cuixq** [comment]
Maybe [`--offline-vulnerabilities`](https://google.github.io/osv-scanner/usage/offline-mode/#offline-option) is what you are looking for? This will avoid sending requests to `osv.dev` but still performing dependency resolution. Remember to specify the data source if you also don't want to send requests to `deps.dev`.
