### ISSUE TITLE
Build GitHub actions for running osv-scanner

### ISSUE THREAD

**Issue by oliverchang** [google/osv-scanner#57]
For running osv-scanner

**Comment by oliverchang** [comment]
(Moving issue to the right repo)

Thanks for proposing this @abhisek! We're still trying to figure out all the necessary requirements for this action (and don't want to rush it), as we want this to go beyond the scope of just scanning (but also include tracking/remediation). 

We're happy to accept contributions to make the necessary plumbing/PR changes for these pieces!

**Comment by abhisek** [comment]
One of the key refactoring change that I would propose is to introduce the following inside `PackageDetails` and have the parser retain this information.

```go
type PackageDetailSource struct {
   sourceFile, sourceLine string
}
```

> It may not be trivial for XML / JSON files where an external format parser is used :(

Subsequently correlate the `vulnerabilityResults` with input packages so that the final result can include a source file and line for each vulnerability. This will allow better consumption of results by annotating source lines in PR using Github (or equivalent) Checks API

**Comment by G-Rath** [comment]
@abhisek that sounds like a pretty huge complexity jump since you'd have to implement custom parsers for at least JSON, YAML, TOML, and XML.

I'd recommend checking out [`check-with-osv-detector`](https://github.com/G-Rath/check-with-osv-detector) as prior art - its a straightforward composite action that pulls the binary from GH releases which is more lightweight than using a docker-based action; now that `osv-scanner` is releasing binaries it should be pretty easy to create an action from that.

**Comment by Dentrax** [comment]
Hey, is this still the case? Has anybody implemented the gh-action yet?

**Comment by oliverchang** [comment]
Thanks @slonka! We're also looking at building officially workflows to run osv-scanner as part of GH Actions soon. @another-rex is the one owning this :)
