### ISSUE TITLE
Markdown in SARIF help text

### ISSUE THREAD

**Issue by fvelcker** [google/osv-scanner#742]
Hello,

I am not sure if I am doing something wrong or if I misunderstand.

The `markdown` help text in the SARIF output is the same as `text` and contains `\n` and other `\u...` and `\`. 
![image](https://github.com/google/osv-scanner/assets/850019/474279f8-acd4-4f6a-8a1d-b6576c7cf8c1)

So if I copy the markdown to paste it in a wiki (Gitlab for instance) it is not interpreted correctly. (I haven't tried yet, but the idea is to create the wiki page via the API from the pipeline).

I am using the docker latest docker image `ghcr.io/google/osv-scanner:latest` (v1,15)

Thanks !

**Comment by another-rex** [comment]
Hello!

The SARIF output is a JSON object, so the markdown and text fields are encoded as JSON string literals (which is why you see `\n`, `\u003e`...etc). If you want to copy and paste the output you'll first need to first decode it. 

You can paste the string (including the `"` quotes) to somewhere like https://codebeautify.org/json-to-text-converter to get the output, or even put `console.log("paste string here")` in the browser console can also work (though in general be careful about pasting things into your console, make sure it's just one continuous string).

If you are passing it through an API it should work with no changes, since the text/markdown data will be interpreted correctly by whatever code is using it.

**Comment by fvelcker** [comment]
Ah! thanks, that makes sense (I feel a bit stupid now :))
