### ISSUE TITLE
Add node_modules artifact extraction

### ISSUE THREAD

**Issue by another-rex** [google/osv-scanner#791]
Add node_modules artifact extraction ability

**Comment by G-Rath** [comment]
@another-rex could you expand a bit on the initial implementation for this? If I recall correctly when we last spoke currently we want to do this using the `node_module/.package-lock.json` file since the interfaces don't currently support walking directories (which also blocks #790 unless Python has a similar file?)

**Comment by another-rex** [comment]
> f I recall correctly when we last spoke currently we want to do this using the node_module/.package-lock.json file since the interfaces don't currently support walking directories (which also blocks https://github.com/google/osv-scanner/issues/790 unless Python has a similar file?)

Yep, let's use `node_modules/.package-lock.json` until we update the extractor interface.

> And should this only happen in containers?

Yes, I think this just means we don't have an init function that runs `registerExtractors()`

**Comment by another-rex** [comment]
For #790, I think .egg-info is a single file (a zip file I believe)? I'm not sure though I haven't looked into it enough. It will prevent us iterating through site-packages / dist-packages folders though.

**Comment by KoenDG** [comment]
Hello, sorry for opening an old issue, but this seems to be about a use case I have.

I'm trying to scan files in `node_module/.package-lock.json` but I'm getting:

> could not determine extractor for ./node_modules/.package-lock.json

I am using the current latest build, 1.8.4, on Ubuntu 20.04

I see talk of only supporting this inside containers, and I have to ask: why? What is the motivation for not allowing such a scan on a regular OS?

My use case is this: I need to scan for vulnerabilities, but I've found that lockfile versions below 3 have incomplete info. `npm ci` says this literally when running it in a code base that has a lockfile of an old version.

>npm WARN old lockfile
>npm WARN old lockfile The package-lock.json file was created with an old version of npm,
>npm WARN old lockfile so supplemental metadata must be fetched from the registry.
>npm WARN old lockfile
>npm WARN old lockfile This is a one-time fix-up, please be patient...
>npm WARN old lockfile

Using `npm ci` is the way to stop regenerating your package-lock.json every time, which is important for consistency, but I still need that updated data. So I thought I'd just let `npm ci` do it's thing and then scan `node_modules/.package-lock.json`. But no such luck.

Guess this is a feature request now: can this be enabled for regular scanning? Outside containers?

**Comment by another-rex** [comment]
@KoenDG 

The main reason not to include .package-lock.json scanning by default is to avoid duplicate results from both your `package-lock.json` and `.package-lock.json`. 

There is no reason not to allow you to manually scan .package-lock.json files directly, other than we haven't implemented that yet. 

A direct workaround is to pass the extractor you want to use directly: https://google.github.io/osv-scanner/usage/#specify-lockfiles  e.g. 
```
osv-scanner -L package-lock.json:./node_modules/.package-lock.json
```

---

I am curious about your reasoning for why you need to scan `node_modules/.package-lock.json` and how that would be better than scanning `package-lock.json`:
1. How is lockfile version 2 incomplete, what new information does version 3 add? 
2. If your npm version is new enough that it will generate a `node_modules/.package-lock.json` at version 3, why do you not update your lockfile to version 3 once, and then continue using `npm ci`?

Thanks!

**Comment by KoenDG** [comment]
@another-rex Thanks for the reply

To address your questions:

1. All I know is that `npm` itself tells me this sometimes. It may well be that I just haven't payed proper attention and there's no actual difference and the warning is maybe only for version 1? Reading the documentation: https://docs.npmjs.com/cli/v10/configuring-npm/package-lock-json

I see this:

> When npm detects a lockfile from npm v6 or before during the package installation process, it is automatically updated to fetch missing information from either the node_modules tree or (in the case of empty node_modules trees or very old lockfile formats) the npm registry.

No explaining what this "missing data" actually is. Regardless, it sort of troubling I can't actually find a changelog for lockfile v3 when googling for it.


2. Because they're not my projects to update. Only to scan and report on. No changing builds you're not a part of, and all that. So I have to leave package.json and package-lock.json alone.

Not great, but the workaround of the file in node_modules makes it work.

And thank you for the command example, it works great.

**Comment by G-Rath** [comment]
> Regardless, it sort of troubling I can't actually find a changelog for lockfile v3 when googling for it.

The key change is that in npm v7 a new dependency tree structure was introduced that's more efficient - that's represented as lockfile v3, and lockfile v2 was introduced to help transitioning from npm <v6 to v7+ by having both the v1 and the v3 dependency trees captured as the cost of twice the size of a v1 or v3 lockfile.

If you look at a v2 lockfile, the new dependency tree [is under the `packages` key, whereas the old dependency tree is under `dependencies`](https://github.com/google/osv-scanner/blob/main/pkg/lockfile/parse-npm-lock.go#L43-L49).

There's no explicit changelog as the tree is something of an implementation detail - the only reason that there are lockfile versions in the first place are to help transitioning since not all codebases would immediately be upgraded to vN lockfile, and it would be super painful especially for folks like e.g. myself whose role includes maintaining a bunch of unrelated codebases to have npm _always_ upgrade a codebase anytime you need to do a minor update like a security patch.

https://github.com/npm/rfcs/pull/434 is probably about as close as you'll find for a changelog
